/* Generated by the Nim Compiler v2.2.12 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI570425846 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI570425844 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI570425843 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI570425664 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI570425667 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217742 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI570425466 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI570425464 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI570425463 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI570425349 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI570425427 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI570425347 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI570425385 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555181 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555189 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555188 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555185 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555186 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI721420291 = {size: 0,kind: 44,base: null,node: null,finalizer: null};
var NTI721420292 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NNI721420292 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a0", len: 0, typ: NTI721420291, name: "a0", sons: null}, 
{kind: 1, offset: "a1", len: 0, typ: NTI721420291, name: "a1", sons: null}]};
NTI721420292.node = NNI721420292;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
var NNI33555186 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555186.node = NNI33555186;
NTI33555188.base = NTI33555185;
NTI33555189.base = NTI33555185;
var NNI33555185 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555188, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555189, name: "up", sons: null}]};
NTI33555185.node = NNI33555185;
var NNI33555181 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555181.node = NNI33555181;
NTI33555185.base = NTI33555181;
NTI33555186.base = NTI33555185;
NTI134217749.base = NTI33555186;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
NTI134217741.base = NTI33555186;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555186;
var NNI570425347 = {kind: 1, offset: "parede", len: 0, typ: NTI33554466, name: "parede", sons: null};
NTI570425347.node = NNI570425347;
NTI570425385.base = NTI570425347;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555186;
var NNI570425427 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}]};
NTI570425427.node = NNI570425427;
var NNI570425349 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}]};
NTI570425349.node = NNI570425349;
var NNI570425463 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI570425464, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI570425466, name: "Field1", sons: null}]};
NTI570425463.node = NNI570425463;
var NNI134217742 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217742.node = NNI134217742;
NTI134217742.base = NTI134217741;
var NNI570425667 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI570425349, name: "Field1", sons: null}]};
NTI570425667.node = NNI570425667;
var NNI570425664 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI570425349, name: "Field1", sons: null}]};
NTI570425664.node = NNI570425664;
var NNI570425843 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI570425844, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI570425846, name: "Field1", sons: null}]};
NTI570425843.node = NNI570425843;
var DefaultRandSeed_721420302 = {a0: 7616934476015405061n, a1: 15122295919272093642n};

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557377 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2925(ti_p2))) {
      result_33557377 = src_p1;
      }
      else {
        result_33557377 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557377 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557377 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557377 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557377 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557377, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557377 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557377 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557377 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557377[i] = nimCopy(result_33557377[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557377 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557377 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557377[i] = nimCopy(result_33557377[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557377 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557377 = src_p1;
      break;
    }

  return result_33557377;

}
                      var helper_721420335 = new BigUint64Array([13739361407582206667n, 15594563132006766882n]);

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function nimAddStrStr(x_p0, y_p1) {
      var L = y_p1.length;
  for (var i = 0; i < L; ++i) {
    x_p0.push(y_p1[i]);
  }
  

  
}

function isObj(obj_p0, subclass_p1) {
  var result_33557490 = false;

  BeforeRet: {
    var x_33557491 = obj_p0;
    if ((x_33557491 == subclass_p1)) {
    result_33557490 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557491 == subclass_p1))) break Label2;
          if ((x_33557491 == null)) {
          result_33557490 = false;
          break BeforeRet;
          }
          
          x_33557491 = x_33557491.base;
        }
    };
    result_33557490 = true;
    break BeforeRet;
  };

  return result_33557490;

}

function toJSStr(s_p0) {
  var result_33556954 = null;

    var res_33557020 = newSeq__system_u2563((s_p0).length);
    var i_33557021 = 0;
    var j_33557022 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33557021 < (s_p0).length)) break Label2;
          var c_33557023 = s_p0[i_33557021];
          if ((c_33557023 < 128)) {
          res_33557020[j_33557022] = String.fromCharCode(c_33557023);
          i_33557021 += 1;
          }
          else {
            var helper_33557049 = newSeq__system_u2563(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33557050 = c_33557023.toString(16);
                  if ((((code_33557050) == null ? 0 : (code_33557050).length) == 1)) {
                  helper_33557049.push("%0");;
                  }
                  else {
                  helper_33557049.push("%");;
                  }
                  
                  helper_33557049.push(code_33557050);;
                  i_33557021 += 1;
                  if ((((s_p0).length <= i_33557021) || (s_p0[i_33557021] < 128))) {
                  break Label3;
                  }
                  
                  c_33557023 = s_p0[i_33557021];
                }
            };
++excHandler;
            try {
            res_33557020[j_33557022] = decodeURIComponent(helper_33557049.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33557020[j_33557022] = helper_33557049.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33557022 += 1;
        }
    };
    if (res_33557020.length < j_33557022) { for (var i = res_33557020.length ; i < j_33557022 ; ++i) res_33557020.push(null); }
               else { res_33557020.length = j_33557022; };
    result_33556954 = res_33557020.join("");

  return result_33556954;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    throw e_p0;

  
}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557412 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557412 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557412;

}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function mulInt(a_p0, b_p1) {
        var result = a_p0 * b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557417 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557417 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557417;

}

function makeNimstrLit(c_p0) {
      var result = [];
  for (var i = 0; i < c_p0.length; ++i) {
    result[i] = c_p0.charCodeAt(i);
  }
  return result;
  

  
}

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function divInt(a_p0, b_p1) {
        if (b_p1 == 0) raiseDivByZero();
    if (b_p1 == -1 && a_p0 == 2147483647) raiseOverflow();
    return Math.trunc(a_p0 / b_p1);
  

  
}

function nimMax(a_p0, b_p1) {
    var Temporary1;

  var result_33557204 = 0;

  BeforeRet: {
    if ((b_p1 <= a_p0)) {
    Temporary1 = a_p0;
    }
    else {
    Temporary1 = b_p1;
    }
    
    result_33557204 = Temporary1;
    break BeforeRet;
  };

  return result_33557204;

}

function modInt(a_p0, b_p1) {
        if (b_p1 == 0) raiseDivByZero();
    if (b_p1 == -1 && a_p0 == 2147483647) raiseOverflow();
    return Math.trunc(a_p0 % b_p1);
  

  
}

function absInt(a_p0) {
    var Temporary1;

  var result_33557193 = 0;

    if ((a_p0 < 0)) {
    Temporary1 = (a_p0 * (-1));
    }
    else {
    Temporary1 = a_p0;
    }
    
    result_33557193 = Temporary1;

  return result_33557193;

}
if (globalThis.utcInstance_905971481 === undefined) {
  globalThis.utcInstance_905971481 = [null];
}
if (globalThis.localInstance_905971482 === undefined) {
  globalThis.localInstance_905971482 = [null];
}

function isFatPointer__system_u2925(ti_p0) {
  var result_33557359 = false;

  BeforeRet: {
    result_33557359 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557359;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}
var state_721420303 = [nimCopy(null, DefaultRandSeed_721420302, NTI721420292)];
var objectID_1207959730 = [0];

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

    var old_335544528 = (result_p0[result_p0_Idx]).length;
    if (result_p0[result_p0_Idx].length < (Temporary1 = (old_335544528 + n_p3), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_335544542 = 0;
      var i_570426595 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_570426595 < n_p3)) break Label4;
            iHEX60gensym4_335544542 = i_570426595;
            result_p0[result_p0_Idx][(old_335544528 + iHEX60gensym4_335544542)] = x_p1.charCodeAt((start_p2 + iHEX60gensym4_335544542));
            i_570426595 += 1;
          }
      };
    };

  
}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));

  
}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));

  
}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));

  
}

function HEX24__systemZdollars_u14(xHEX60gensym0_p0) {
  var result_402653200 = [[]];

    result_402653200[0] = nimCopy(null, [], NTI33554449);
    addInt__stdZprivateZdigitsutils_u241(result_402653200, 0, xHEX60gensym0_p0);

  return result_402653200[0];

}

function add__system_u1973(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function newSeq__system_u2563(len_p0) {
  var result_33556999 = [];

    result_33556999 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556999[i] = null; }
  return result_33556999;

}

function isNimException__system_u2048() {
    return lastJSError && lastJSError.m_type;

  
}

function getCurrentException() {
  var result_33556483 = null;

    if (isNimException__system_u2048()) {
    result_33556483 = lastJSError;
    }
    

  return result_33556483;

}

function raiseDefect() {
    if (isNimException__system_u2048()) {
    var e_33556699 = getCurrentException();
    if (isObj(e_33556699.m_type, NTI33555186)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556699);
    }
    
    throw e_33556699;
    }
    
    }
    

  
}

function unhandledException(e_p0) {
    var buf_33556693 = [[]];
    if (!(((e_p0.message).length == 0))) {
    nimAddStrStr(buf_33556693[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    nimAddStrStr(buf_33556693[0], e_p0.message);;
    }
    else {
    nimAddStrStr(buf_33556693[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    nimAddStrStr(buf_33556693[0], [32,91]);;
    add__system_u1973(buf_33556693, 0, e_p0.name);
    nimAddStrStr(buf_33556693[0], [93,10]);;
    var cbuf_33556694 = toJSStr(buf_33556693[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556694);
  }
  else {
    throw cbuf_33556694;
  }
  

  
}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u14(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u14(a_p1),[32,46,46,32],HEX24__systemZdollars_u14(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function rotl__pureZrandom_u24(x_p0, k_p1) {
  var result_721420315 = 0n;

    result_721420315 = (BigInt.asUintN(64, x_p0 << (BigInt(k_p1) & 63n)) | (x_p0 >> (BigInt(BigInt.asUintN(64, (64n - k_p1))) & 63n)));

  return result_721420315;

}

function next__pureZrandom_u36(r_p0) {
  var result_721420326 = 0n;

    var s0_721420327 = r_p0.a0;
    var s1_721420328 = r_p0.a1;
    result_721420326 = BigInt.asUintN(64, (s0_721420327 + s1_721420328));
    s1_721420328 = (s1_721420328 ^ s0_721420327);
    r_p0.a0 = ((rotl__pureZrandom_u24(s0_721420327, 55n) ^ s1_721420328) ^ BigInt.asUintN(64, s1_721420328 << (BigInt(14) & 63n)));
    r_p0.a1 = rotl__pureZrandom_u24(s1_721420328, 36n);

  return result_721420326;

}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function skipRandomNumbers__pureZrandom_u45(s_p0) {
    var s0_721420336 = 0n;
    var s1_721420337 = 0n;
    Label1: {
      var i_721420346 = 0;
      var res_570426589 = 0;
      Label2: {
          Label3: while (true) {
          if (!(res_570426589 <= 1)) break Label3;
            i_721420346 = res_570426589;
            Label4: {
              var b_721420351 = 0;
              var i_570426587 = 0;
              Label5: {
                  Label6: while (true) {
                  if (!(i_570426587 < 64)) break Label6;
                    b_721420351 = i_570426587;
                    if (!(((helper_721420335[chckIndx(i_721420346, 0, (helper_721420335).length - 1)] & BigInt.asUintN(64, 1n << (BigInt(BigInt.asUintN(64, BigInt(b_721420351))) & 63n))) == 0n))) {
                    s0_721420336 = (s0_721420336 ^ s_p0.a0);
                    s1_721420337 = (s1_721420337 ^ s_p0.a1);
                    }
                    
                    (next__pureZrandom_u36(s_p0));
                    i_570426587 = addInt(i_570426587, 1);
                  }
              };
            };
            res_570426589 = addInt(res_570426589, 1);
          }
      };
    };
    s_p0.a0 = s0_721420336;
    s_p0.a1 = s1_721420337;

  
}

function initRand__pureZrandom_u250(seed_p0) {
    var Temporary1;

  var result_721420540 = [({a0: 0n, a1: 0n})];

    if (!((seed_p0 == 0n))) {
    Temporary1 = seed_p0;
    }
    else {
    Temporary1 = 2147483647n;
    }
    
    var seed_721420546 = Temporary1;
    result_721420540[0] = nimCopy(result_721420540[0], {a0: BigInt.asUintN(64, (seed_721420546 >> (BigInt(16) & 63n))), a1: BigInt.asUintN(64, (seed_721420546 & 65535n))}, NTI721420292);
    skipRandomNumbers__pureZrandom_u45(result_721420540[0]);
    (next__pureZrandom_u36(result_721420540[0]));

  return result_721420540[0];

}

function newSeq__labirinto_u68(len_p0) {
  var result_570425416 = [];

    result_570425416 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_570425416[i] = ({parede: false}); }
  return result_570425416;

}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function sysFatal__stdZassertions_u46(message_p1) {
    raiseException({message: nimCopy(null, message_p1, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");

  
}

function raiseAssert__stdZassertions_u44(msg_p0) {
    sysFatal__stdZassertions_u46(msg_p0);

  
}

function failedAssertImpl__stdZassertions_u86(msg_p0) {
    raiseAssert__stdZassertions_u44(msg_p0);

  
}

function idx__labirinto_u18(lab_p0, x_p1, y_p2) {
  var result_570425366 = 0;

    result_570425366 = addInt(mulInt(y_p2, lab_p0.largura), x_p1);

  return result_570425366;

}

function HEX5BHEX5D__labirinto_u141(s_p0, i_p1) {
  var result_570425489 = null;

    result_570425489 = (s_p0).base[(s_p0).off + chckIndx(subInt((s_p0).len, i_p1), 0, (s_p0).len - 1)];

  return result_570425489;

}

function dentro__labirinto_u23(lab_p0, x_p1, y_p2) {
  var result_570425371 = false;

    result_570425371 = ((((0 <= x_p1) && (0 <= y_p2)) && (x_p1 < lab_p0.largura)) && (y_p2 < lab_p0.altura));

  return result_570425371;

}

function parede__labirinto_u28(lab_p0, x_p1, y_p2) {
  var result_570425376 = false;

    result_570425376 = (!(dentro__labirinto_u23(lab_p0, x_p1, y_p2)) || lab_p0.celulas[chckIndx(idx__labirinto_u18(lab_p0, x_p1, y_p2), 0, (lab_p0.celulas).length - 1)].parede);

  return result_570425376;

}

function pop__labirinto_u227(s_p0, s_p0_Idx) {
  var result_570425574 = {Field0: 0, Field1: 0};

    var L_570425578 = subInt((s_p0[s_p0_Idx]).length, 1);
    result_570425574 = nimCopy(result_570425574, s_p0[s_p0_Idx][chckIndx(L_570425578, 0, (s_p0[s_p0_Idx]).length - 1)], NTI570425349);
    if (s_p0[s_p0_Idx].length < chckRange(L_570425578, 0, 2147483647)) { for (var i = s_p0[s_p0_Idx].length ; i < chckRange(L_570425578, 0, 2147483647) ; ++i) s_p0[s_p0_Idx].push({Field0: 0, Field1: 0}); }
               else { s_p0[s_p0_Idx].length = chckRange(L_570425578, 0, 2147483647); };

  return result_570425574;

}

function rand__pureZrandom_u112(r_p0, max_p1) {
  var result_721420404 = 0n;

  BeforeRet: {
    if ((max_p1 == 0n)) {
    break BeforeRet;
    }
    else {
      var max_721420405 = max_p1;
      if ((max_721420405 == 18446744073709551615n)) {
      result_721420404 = next__pureZrandom_u36(r_p0);
      break BeforeRet;
      }
      
      var iters_721420418 = 0;
      Label1: {
          Label2: while (true) {
          if (!true) break Label2;
            var x_721420419 = next__pureZrandom_u36(r_p0);
            if (((x_721420419 <= BigInt.asUintN(64, (18446744073709551615n - (18446744073709551615n % max_721420405)))) || (20 < iters_721420418))) {
            result_721420404 = (x_721420419 % BigInt.asUintN(64, (max_721420405 + 1n)));
            break BeforeRet;
            }
            else {
            iters_721420418 = addInt(iters_721420418, 1);
            }
            
          }
      };
    }
    
  };

  return result_721420404;

}

function rand__pureZrandom_u108(r_p0, max_p1) {
  var result_721420399 = 0;

    result_721420399 = Number(BigInt.asIntN(32, rand__pureZrandom_u112(r_p0, BigInt.asUintN(64, BigInt(max_p1)))));

  return result_721420399;

}

function raiseDivByZero() {
    raiseException({message: [100,105,118,105,115,105,111,110,32,98,121,32,122,101,114,111], parent: null, m_type: NTI134217742, name: null, trace: [], up: null}, "DivByZeroDefect");

  
}

function gerar__labirinto_u33(largura_p0, altura_p1, semente_p2, aberturaPct_p3) {
                    var Temporary10;

  var result_570425382 = ({largura: 0, altura: 0, celulas: []});

    var rng_570425383 = [initRand__pureZrandom_u250(BigInt(semente_p2))];
    result_570425382.largura = largura_p0;
    result_570425382.altura = altura_p1;
    result_570425382.celulas = nimCopy(null, newSeq__labirinto_u68(chckRange(mulInt(largura_p0, altura_p1), 0, 2147483647)), NTI570425385);
    Label1: {
      var c_570425475 = null;
      var i_570426566 = 0;
      var L_570426567 = (result_570425382.celulas).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570426566 < L_570426567)) break Label3;
            c_570425475 = result_570425382.celulas[chckIndx(i_570426566, 0, (result_570425382.celulas).length - 1)];
            c_570425475.parede = true;
            i_570426566 += 1;
            if (!(((result_570425382.celulas).length == L_570426567))) {
            failedAssertImpl__stdZassertions_u86(makeNimstrLit("iterators.nim(263, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    var pilha_570425480 = [[nimCopy(null, {Field0: 1, Field1: 1}, NTI570425427)]];
    result_570425382.celulas[chckIndx(idx__labirinto_u18(result_570425382, 1, 1), 0, (result_570425382.celulas).length - 1)].parede = false;
    Label4: {
        Label5: while (true) {
        if (!(0 < (pilha_570425480[0]).length)) break Label5;
          Label6: {
            var tmpTuple_570425510 = nimCopy(null, HEX5BHEX5D__labirinto_u141({base: pilha_570425480[0], off: 0, len: (pilha_570425480[0]).length}, 1), NTI570425349);
            var x_570425511 = tmpTuple_570425510["Field0"];
            var y_570425512 = tmpTuple_570425510["Field1"];
            var vizinhos_570425517 = [];
            Label7: {
              var dx_570425560 = 0;
              var dy_570425561 = 0;
              var i_570426573 = 0;
              Label8: {
                  Label9: while (true) {
                  if (!true) break Label9;
                    var colontmp__570426576 = (Temporary10 = [nimCopy(null, {Field0: 0, Field1: (-2)}, NTI570425463), nimCopy(null, {Field0: 2, Field1: 0}, NTI570425463), nimCopy(null, {Field0: 0, Field1: 2}, NTI570425463), nimCopy(null, {Field0: (-2), Field1: 0}, NTI570425463)], Temporary10)[chckIndx(i_570426573, 0, (Temporary10).length - 1)];
                    dx_570425560 = colontmp__570426576["Field0"];
                    dy_570425561 = colontmp__570426576["Field1"];
                    var nx_570425562 = addInt(x_570425511, dx_570425560);
                    var ny_570425563 = addInt(y_570425512, dy_570425561);
                    if ((dentro__labirinto_u23(result_570425382, nx_570425562, ny_570425563) && parede__labirinto_u28(result_570425382, nx_570425562, ny_570425563))) {
                    vizinhos_570425517.push({Field0: nx_570425562, Field1: ny_570425563});;
                    }
                    
                    if ((3 <= i_570426573)) {
                    break Label8;
                    }
                    
                    i_570426573 += 1;
                  }
              };
            };
            if (((vizinhos_570425517).length == 0)) {
            (pop__labirinto_u227(pilha_570425480, 0));
            break Label6;
            }
            
            var escolhido_570425586 = nimCopy(null, vizinhos_570425517[chckIndx(rand__pureZrandom_u108(rng_570425383[0], chckRange(subInt((vizinhos_570425517).length, 1), 0, 2147483647)), 0, (vizinhos_570425517).length - 1)], NTI570425349);
            result_570425382.celulas[chckIndx(idx__labirinto_u18(result_570425382, divInt(addInt(x_570425511, escolhido_570425586.Field0), 2), divInt(addInt(y_570425512, escolhido_570425586.Field1), 2)), 0, (result_570425382.celulas).length - 1)].parede = false;
            result_570425382.celulas[chckIndx(idx__labirinto_u18(result_570425382, escolhido_570425586.Field0, escolhido_570425586.Field1), 0, (result_570425382.celulas).length - 1)].parede = false;
            var Temporary11 = nimCopy(null, escolhido_570425586, NTI570425349);
            pilha_570425480[0].push(Temporary11);;
          };
        }
    };
    if ((0 < aberturaPct_p3)) {
    Label12: {
      var y_570425595 = 0;
      var colontmp__570426582 = 0;
      colontmp__570426582 = subInt(altura_p1, 1);
      var i_570426583 = 1;
      Label13: {
          Label14: while (true) {
          if (!(i_570426583 < colontmp__570426582)) break Label14;
            y_570425595 = i_570426583;
            Label15: {
              var x_570425600 = 0;
              var colontmp__570426579 = 0;
              colontmp__570426579 = subInt(largura_p0, 1);
              var i_570426580 = 1;
              Label16: {
                  Label17: while (true) {
                  if (!(i_570426580 < colontmp__570426579)) break Label17;
                    x_570425600 = i_570426580;
                    if ((parede__labirinto_u28(result_570425382, x_570425600, y_570425595) && (rand__pureZrandom_u108(rng_570425383[0], 99) < aberturaPct_p3))) {
                    result_570425382.celulas[chckIndx(idx__labirinto_u18(result_570425382, x_570425600, y_570425595), 0, (result_570425382.celulas).length - 1)].parede = false;
                    }
                    
                    i_570426580 = addInt(i_570426580, 1);
                  }
              };
            };
            i_570426583 = addInt(i_570426583, 1);
          }
      };
    };
    }
    

  return result_570425382;

}

function newSeq__labirinto_u414(len_p0) {
  var result_570425762 = [];

    result_570425762 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_570425762[i] = 0; }
  return result_570425762;

}

function newSeq__labirinto_u549(len_p0) {
  var result_570425897 = [];

    result_570425897 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_570425897[i] = {Field0: 0, Field1: {Field0: 0, Field1: 0}}; }
  return result_570425897;

}

function HEX2A__pureZalgorithm_u8(x_p0, order_p1) {
  var result_704643083 = 0;

    var y_704643088 = subInt(order_p1, 1);
    result_704643083 = subInt((x_p0 ^ y_704643088), y_704643088);

  return result_704643083;

}

function mergeAlt__labirinto_u595(a_p0, b_p1, lo_p2, m_p3, hi_p4, cmp_p5, order_p6) {
  BeforeRet: {
    if ((HEX2A__pureZalgorithm_u8(cmp_p5((a_p0).base[(a_p0).off + chckIndx(m_p3, 0, (a_p0).len - 1)], (a_p0).base[(a_p0).off + chckIndx(addInt(m_p3, 1), 0, (a_p0).len - 1)]), order_p6) <= 0)) {
    break BeforeRet;
    }
    
    var j_570425950 = lo_p2;
    if (!((j_570425950 <= m_p3))) {
    failedAssertImpl__stdZassertions_u86([97,108,103,111,114,105,116,104,109,46,110,105,109,40,51,51,56,44,32,51,41,32,96,106,32,60,61,32,109,96,32]);
    }
    
    var bb_570425956 = 0;
    Label1: {
        Label2: while (true) {
        if (!(j_570425950 <= m_p3)) break Label2;
          (b_p1).base[(b_p1).off + chckIndx(bb_570425956, 0, (b_p1).len - 1)] = nimCopy((b_p1).base[(b_p1).off + chckIndx(bb_570425956, 0, (b_p1).len - 1)], (a_p0).base[(a_p0).off + chckIndx(j_570425950, 0, (a_p0).len - 1)], NTI570425664);
          bb_570425956 = addInt(bb_570425956, 1);
          j_570425950 = addInt(j_570425950, 1);
        }
    };
    var i_570425967 = 0;
    var k_570425968 = lo_p2;
    Label3: {
        Label4: while (true) {
        if (!((k_570425968 < j_570425950) && (j_570425950 <= hi_p4))) break Label4;
          if ((HEX2A__pureZalgorithm_u8(cmp_p5((b_p1).base[(b_p1).off + chckIndx(i_570425967, 0, (b_p1).len - 1)], (a_p0).base[(a_p0).off + chckIndx(j_570425950, 0, (a_p0).len - 1)]), order_p6) <= 0)) {
          (a_p0).base[(a_p0).off + chckIndx(k_570425968, 0, (a_p0).len - 1)] = nimCopy((a_p0).base[(a_p0).off + chckIndx(k_570425968, 0, (a_p0).len - 1)], (b_p1).base[(b_p1).off + chckIndx(i_570425967, 0, (b_p1).len - 1)], NTI570425664);
          i_570425967 = addInt(i_570425967, 1);
          }
          else {
            (a_p0).base[(a_p0).off + chckIndx(k_570425968, 0, (a_p0).len - 1)] = nimCopy((a_p0).base[(a_p0).off + chckIndx(k_570425968, 0, (a_p0).len - 1)], (a_p0).base[(a_p0).off + chckIndx(j_570425950, 0, (a_p0).len - 1)], NTI570425664);
            j_570425950 = addInt(j_570425950, 1);
          }
          
          k_570425968 = addInt(k_570425968, 1);
        }
    };
    Label5: {
        Label6: while (true) {
        if (!(k_570425968 < j_570425950)) break Label6;
          (a_p0).base[(a_p0).off + chckIndx(k_570425968, 0, (a_p0).len - 1)] = nimCopy((a_p0).base[(a_p0).off + chckIndx(k_570425968, 0, (a_p0).len - 1)], (b_p1).base[(b_p1).off + chckIndx(i_570425967, 0, (b_p1).len - 1)], NTI570425664);
          k_570425968 = addInt(k_570425968, 1);
          i_570425967 = addInt(i_570425967, 1);
        }
    };
  };

  
}

function sort__labirinto_u508(a_p0, cmp_p1, order_p2) {
    var n_570425864 = (a_p0).len;
    var b_570425936 = newSeq__labirinto_u549(chckRange(divInt(n_570425864, 2), 0, 2147483647));
    var s_570425937 = 1;
    Label1: {
        Label2: while (true) {
        if (!(s_570425937 < n_570425864)) break Label2;
          var m_570425938 = subInt(subInt(n_570425864, 1), s_570425937);
          Label3: {
              Label4: while (true) {
              if (!(0 <= m_570425938)) break Label4;
                mergeAlt__labirinto_u595(a_p0, {base: b_570425936, off: 0, len: (b_570425936).length}, nimMax(addInt(subInt(m_570425938, s_570425937), 1), 0), m_570425938, addInt(m_570425938, s_570425937), cmp_p1, order_p2);
                m_570425938 = subInt(m_570425938, mulInt(s_570425937, 2));
              }
          };
          s_570425937 = mulInt(s_570425937, 2);
        }
    };

  
}

function cmp__system_u3676(x_p0, y_p1) {
  var result_33558112 = 0;

  BeforeRet: {
    if ((x_p0 == y_p1)) {
    result_33558112 = 0;
    break BeforeRet;
    }
    
    if ((x_p0 < y_p1)) {
    result_33558112 = (-1);
    break BeforeRet;
    }
    
    result_33558112 = 1;
    break BeforeRet;
  };

  return result_33558112;

}

function delete__labirinto_u671(x_p0, x_p0_Idx, i_p1) {
    if (((x_p0[x_p0_Idx]).length - 1 < i_p1)) {
    raiseException({message: ([105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,58,32,39]).concat(HEX24__systemZdollars_u14(i_p1),[39,32,60,32,39],HEX24__systemZdollars_u14((x_p0[x_p0_Idx]).length),[39,32,102,97,105,108,101,100]), m_type: NTI134217749, parent: null, name: null, trace: [], up: null}, "IndexDefect");
    }
    
    x_p0[x_p0_Idx].splice(i_p1, 1);

  
}

function HEX3DHEX3D__labirinto_u703(x_p0, y_p1) {
  var result_570426051 = false;

  BeforeRet: {
    if (true) {
    if (!((x_p0["Field0"] == y_p1["Field0"]))) {
    result_570426051 = false;
    break BeforeRet;
    }
    
    }
    
    if (true) {
    if (!((x_p0["Field1"] == y_p1["Field1"]))) {
    result_570426051 = false;
    break BeforeRet;
    }
    
    }
    
    result_570426051 = true;
    break BeforeRet;
  };

  return result_570426051;

}

function reverse__labirinto_u733(a_p0, first_p1, last_p2) {
    var x_570426082 = first_p1;
    var y_570426083 = last_p2;
    Label1: {
        Label2: while (true) {
        if (!(x_570426082 < y_570426083)) break Label2;
          var HEX3Atmp_570426625 = nimCopy(null, (a_p0).base[(a_p0).off + chckIndx(x_570426082, 0, (a_p0).len - 1)], NTI570425349);
          (a_p0).base[(a_p0).off + chckIndx(x_570426082, 0, (a_p0).len - 1)] = nimCopy((a_p0).base[(a_p0).off + chckIndx(x_570426082, 0, (a_p0).len - 1)], (a_p0).base[(a_p0).off + chckIndx(y_570426083, 0, (a_p0).len - 1)], NTI570425349);
          (a_p0).base[(a_p0).off + chckIndx(y_570426083, 0, (a_p0).len - 1)] = nimCopy((a_p0).base[(a_p0).off + chckIndx(y_570426083, 0, (a_p0).len - 1)], HEX3Atmp_570426625, NTI570425349);
          y_570426083 = subInt(y_570426083, 1);
          x_570426082 = addInt(x_570426082, 1);
        }
    };

  
}

function reverse__labirinto_u727(a_p0) {
    reverse__labirinto_u733(a_p0, 0, chckRange(nimMax(0, (a_p0).len - 1), 0, 2147483647));

  
}

function manhattan__labirinto_u368(a_p0, b_p1) {
  var result_570425715 = 0;

    result_570425715 = addInt(absInt(subInt(a_p0.Field0, b_p1.Field0)), absInt(subInt(a_p0.Field1, b_p1.Field1)));

  return result_570425715;

}

function buscar__labirinto_u372(lab_p0, inicio_p1, destino_p2, comHeuristica_p3) {
          var Temporary6;

function HEX3Aanonymous__labirinto_u496(a_p0, b_p1) {
  var result_570425845 = 0;

    result_570425845 = cmp__system_u3676(a_p0.Field0, b_p1.Field0);

  return result_570425845;

}
                  var Temporary15;
                    var Temporary17;

  var result_570425721 = ({caminho: [], visitados: [], encontrou: false});

  BeforeRet: {
    var custo_570425783 = newSeq__labirinto_u414(chckRange((lab_p0.celulas).length, 0, 2147483647));
    var veioDe_570425819 = newSeq__labirinto_u414(chckRange((lab_p0.celulas).length, 0, 2147483647));
    Label1: {
      var i_570425828 = 0;
      var colontmp__570426602 = 0;
      colontmp__570426602 = (custo_570425783).length;
      var i_570426603 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570426603 < colontmp__570426602)) break Label3;
            i_570425828 = i_570426603;
            custo_570425783[chckIndx(i_570425828, 0, (custo_570425783).length - 1)] = 1073741823;
            veioDe_570425819[chckIndx(i_570425828, 0, (veioDe_570425819).length - 1)] = (-1);
            i_570426603 = addInt(i_570426603, 1);
          }
      };
    };
    custo_570425783[chckIndx(idx__labirinto_u18(lab_p0, inicio_p1.Field0, inicio_p1.Field1), 0, (custo_570425783).length - 1)] = 0;
    var fronteira_570425835 = [[nimCopy(null, {Field0: 0, Field1: nimCopy(null, inicio_p1, NTI570425349)}, NTI570425667)]];
    Label4: {
        Label5: while (true) {
        if (!(0 < (fronteira_570425835[0]).length)) break Label5;
          Temporary6 = HEX3Aanonymous__labirinto_u496.bind(null); Temporary6.ClP_0 = HEX3Aanonymous__labirinto_u496; Temporary6.ClE_0 = null;
          sort__labirinto_u508({base: fronteira_570425835[0], off: 0, len: (fronteira_570425835[0]).length}, Temporary6, 1);
          var atual_570426014 = nimCopy(null, fronteira_570425835[0][chckIndx(0, 0, (fronteira_570425835[0]).length - 1)].Field1, NTI570425349);
          delete__labirinto_u671(fronteira_570425835, 0, 0);
          var Temporary7 = nimCopy(null, atual_570426014, NTI570425349);
          result_570425721.visitados.push(Temporary7);;
          if (HEX3DHEX3D__labirinto_u703(atual_570426014, destino_p2)) {
          result_570425721.encontrou = true;
          var p_570426057 = nimCopy(null, destino_p2, NTI570425349);
          Label8: {
              Label9: while (true) {
              if (!!(HEX3DHEX3D__labirinto_u703(p_570426057, inicio_p1))) break Label9;
                var Temporary10 = nimCopy(null, p_570426057, NTI570425349);
                result_570425721.caminho.push(Temporary10);;
                var anterior_570426066 = veioDe_570425819[chckIndx(idx__labirinto_u18(lab_p0, p_570426057.Field0, p_570426057.Field1), 0, (veioDe_570425819).length - 1)];
                var colontmp__570426607 = modInt(anterior_570426066, lab_p0.largura);
                var colontmp__570426608 = divInt(anterior_570426066, lab_p0.largura);
                p_570426057 = nimCopy(p_570426057, {Field0: colontmp__570426607, Field1: colontmp__570426608}, NTI570425349);
              }
          };
          var Temporary11 = nimCopy(null, inicio_p1, NTI570425349);
          result_570425721.caminho.push(Temporary11);;
          reverse__labirinto_u727({base: result_570425721.caminho, off: 0, len: (result_570425721.caminho).length});
          break BeforeRet;
          }
          
          Label12: {
            var dx_570426102 = 0;
            var dy_570426103 = 0;
            var i_570426611 = 0;
            Label13: {
                Label14: while (true) {
                if (!true) break Label14;
                  var colontmp__570426614 = (Temporary15 = [nimCopy(null, {Field0: 0, Field1: (-1)}, NTI570425843), nimCopy(null, {Field0: 1, Field1: 0}, NTI570425843), nimCopy(null, {Field0: 0, Field1: 1}, NTI570425843), nimCopy(null, {Field0: (-1), Field1: 0}, NTI570425843)], Temporary15)[chckIndx(i_570426611, 0, (Temporary15).length - 1)];
                  dx_570426102 = colontmp__570426614["Field0"];
                  dy_570426103 = colontmp__570426614["Field1"];
                  Label16: {
                    var nx_570426104 = addInt(atual_570426014.Field0, dx_570426102);
                    var ny_570426105 = addInt(atual_570426014.Field1, dy_570426103);
                    if (parede__labirinto_u28(lab_p0, nx_570426104, ny_570426105)) {
                    break Label16;
                    }
                    
                    var novoCusto_570426106 = addInt(custo_570425783[chckIndx(idx__labirinto_u18(lab_p0, atual_570426014.Field0, atual_570426014.Field1), 0, (custo_570425783).length - 1)], 1);
                    if ((novoCusto_570426106 < custo_570425783[chckIndx(idx__labirinto_u18(lab_p0, nx_570426104, ny_570426105), 0, (custo_570425783).length - 1)])) {
                    custo_570425783[chckIndx(idx__labirinto_u18(lab_p0, nx_570426104, ny_570426105), 0, (custo_570425783).length - 1)] = novoCusto_570426106;
                    veioDe_570425819[chckIndx(idx__labirinto_u18(lab_p0, nx_570426104, ny_570426105), 0, (veioDe_570425819).length - 1)] = idx__labirinto_u18(lab_p0, atual_570426014.Field0, atual_570426014.Field1);
                    if (comHeuristica_p3) {
                    Temporary17 = addInt(novoCusto_570426106, manhattan__labirinto_u368({Field0: nx_570426104, Field1: ny_570426105}, destino_p2));
                    }
                    else {
                    Temporary17 = novoCusto_570426106;
                    }
                    
                    var prioridade_570426107 = Temporary17;
                    fronteira_570425835[0].push({Field0: prioridade_570426107, Field1: {Field0: nx_570426104, Field1: ny_570426105}});;
                    }
                    
                  };
                  if ((3 <= i_570426611)) {
                  break Label13;
                  }
                  
                  i_570426611 += 1;
                }
            };
          };
        }
    };
  };

  return result_570425721;

}

function paraJs__labirinto_u816(lab_p0, r_p1) {
  var result_570426163 = null;

    var paredes_570426197 = {};
    Label1: {
      var i_570426238 = 0;
      var c_570426239 = ({parede: false});
      var i_570426628 = 0;
      var L_570426629 = (lab_p0.celulas).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570426628 < L_570426629)) break Label3;
            i_570426238 = i_570426628;
            c_570426239 = lab_p0.celulas[chckIndx(i_570426628, 0, (lab_p0.celulas).length - 1)];
            paredes_570426197[i_570426238] = c_570426239.parede;
            i_570426628 += 1;
            if (!(((lab_p0.celulas).length == L_570426629))) {
            failedAssertImpl__stdZassertions_u86(makeNimstrLit("iterators.nim(187, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    var caminho_570426316 = {};
    Label4: {
      var i_570426340 = 0;
      var p_570426341 = {Field0: 0, Field1: 0};
      var i_570426633 = 0;
      var L_570426634 = (r_p1.caminho).length;
      Label5: {
          Label6: while (true) {
          if (!(i_570426633 < L_570426634)) break Label6;
            i_570426340 = i_570426633;
            p_570426341 = r_p1.caminho[chckIndx(i_570426633, 0, (r_p1.caminho).length - 1)];
            caminho_570426316[i_570426340] = addInt(mulInt(p_570426341.Field1, lab_p0.largura), p_570426341.Field0);
            i_570426633 += 1;
            if (!(((r_p1.caminho).length == L_570426634))) {
            failedAssertImpl__stdZassertions_u86(makeNimstrLit("iterators.nim(187, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    var visitados_570426418 = {};
    Label7: {
      var i_570426424 = 0;
      var p_570426425 = {Field0: 0, Field1: 0};
      var i_570426637 = 0;
      var L_570426638 = (r_p1.visitados).length;
      Label8: {
          Label9: while (true) {
          if (!(i_570426637 < L_570426638)) break Label9;
            i_570426424 = i_570426637;
            p_570426425 = r_p1.visitados[chckIndx(i_570426637, 0, (r_p1.visitados).length - 1)];
            visitados_570426418[i_570426424] = addInt(mulInt(p_570426425.Field1, lab_p0.largura), p_570426425.Field0);
            i_570426637 += 1;
            if (!(((r_p1.visitados).length == L_570426638))) {
            failedAssertImpl__stdZassertions_u86(makeNimstrLit("iterators.nim(187, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    result_570426163 = {};
    result_570426163["largura"] = lab_p0.largura;
    result_570426163["altura"] = lab_p0.altura;
    result_570426163["paredes"] = paredes_570426197;
    result_570426163["caminho"] = caminho_570426316;
    result_570426163["visitados"] = visitados_570426418;
    result_570426163["passosCaminho"] = (r_p1.caminho).length;
    result_570426163["passosVisitados"] = (r_p1.visitados).length;
    result_570426163["encontrou"] = r_p1.encontrou;

  return result_570426163;

}

function nimResolver(largura_p0, altura_p1, semente_p2, aberturaPct_p3, comHeuristica_p4) {
  var result_570426523 = null;

    var lab_570426524 = gerar__labirinto_u33(largura_p0, altura_p1, semente_p2, aberturaPct_p3);
    var inicio_570426525 = {Field0: 1, Field1: 1};
    var destino_570426526 = {Field0: (subInt(largura_p0, 2) | 1), Field1: (subInt(altura_p1, 2) | 1)};
    var r_570426527 = buscar__labirinto_u372(lab_570426524, inicio_570426525, destino_570426526, comHeuristica_p4);
    result_570426523 = paraJs__labirinto_u816(lab_570426524, r_570426527);

  return result_570426523;

}
globalThis.nimResolver = nimResolver;
globalThis.nimPronto = true;
